remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one

title: Gilbert MONTCHO
description: Passionate with exploring data to discover insights and to equip organizations with contextual counseling that maximize their impact and return on investment.

logo: /assets/img/logo.png

header_pages:
  - about.md
  - posts.md

author:
  name: Gilbert M
  email: "gilbert@example.com"


  minima:
  social_links:
    twitter: jekyllrb
    github: jekyll
    linkedin: jekyll
